BEGIN;

DROP TABLE IF EXISTS audit.audit_logs;
DROP TABLE IF EXISTS integration.outbox_events;
DROP TABLE IF EXISTS file.attachments;
DROP TABLE IF EXISTS subcontract.factory_claims;
DROP TABLE IF EXISTS subcontract.sample_approvals;
DROP TABLE IF EXISTS subcontract.material_issue_lines;
DROP TABLE IF EXISTS subcontract.material_issues;
DROP TABLE IF EXISTS subcontract.subcontract_orders;
DROP TABLE IF EXISTS returns.return_dispositions;
DROP TABLE IF EXISTS returns.return_order_lines;
DROP TABLE IF EXISTS returns.return_orders;
DROP TABLE IF EXISTS shipping.scan_events;
DROP TABLE IF EXISTS shipping.carrier_manifest_lines;
DROP TABLE IF EXISTS shipping.carrier_manifests;
DROP TABLE IF EXISTS shipping.shipments;
DROP TABLE IF EXISTS sales.sales_order_lines;
DROP TABLE IF EXISTS sales.sales_orders;
DROP TABLE IF EXISTS qc.batch_quality_statuses;
DROP TABLE IF EXISTS qc.inspections;
DROP TABLE IF EXISTS inventory.warehouse_daily_closings;
DROP TABLE IF EXISTS inventory.stock_counts;
DROP TABLE IF EXISTS inventory.stock_reservations;
DROP TABLE IF EXISTS inventory.stock_balances;
DROP TABLE IF EXISTS inventory.stock_ledger;
DROP FUNCTION IF EXISTS inventory.require_stock_balance_write_context();
DROP FUNCTION IF EXISTS inventory.prevent_stock_ledger_mutation();
DROP TABLE IF EXISTS inventory.goods_receipt_lines;
DROP TABLE IF EXISTS inventory.goods_receipts;
DROP TABLE IF EXISTS inventory.batches;
DROP TABLE IF EXISTS purchase.purchase_order_lines;
DROP TABLE IF EXISTS purchase.purchase_orders;
DROP TABLE IF EXISTS mdm.carriers;
DROP TABLE IF EXISTS mdm.warehouse_bins;
DROP TABLE IF EXISTS mdm.warehouse_zones;
DROP TABLE IF EXISTS mdm.warehouses;
DROP TABLE IF EXISTS mdm.items;
DROP TABLE IF EXISTS mdm.customers;
DROP TABLE IF EXISTS mdm.suppliers;
DROP TABLE IF EXISTS mdm.units;
DROP TABLE IF EXISTS core.document_sequences;
DROP TABLE IF EXISTS core.idempotency_keys;
DROP TABLE IF EXISTS core.user_roles;
DROP TABLE IF EXISTS core.role_permissions;
DROP TABLE IF EXISTS core.permissions;
DROP TABLE IF EXISTS core.roles;
DROP TABLE IF EXISTS core.users;
DROP TABLE IF EXISTS core.organizations;

ALTER TABLE IF EXISTS audit.audit_logs_legacy_000001 RENAME TO audit_logs;
ALTER TABLE IF EXISTS inventory.stock_ledger_legacy_000001 RENAME TO stock_ledger;

DROP SCHEMA IF EXISTS integration;
DROP SCHEMA IF EXISTS file;
DROP SCHEMA IF EXISTS subcontract;
DROP SCHEMA IF EXISTS returns;
DROP SCHEMA IF EXISTS shipping;
DROP SCHEMA IF EXISTS sales;
DROP SCHEMA IF EXISTS qc;
DROP SCHEMA IF EXISTS purchase;
DROP SCHEMA IF EXISTS mdm;
DROP SCHEMA IF EXISTS core;

COMMIT;
